### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by rajivharlalka** [casbin/casbin#1160]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**
Your answer here

**Your model:**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
u = _,_

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = u(r.sub,p.sub) && r.obj == p.obj && r.act == p.act
```

**Your policy:**

```
p, alice, book, read
p, bob, book, read
p, bob, book, write
p, alice, pen, get
p, bob, pen, get
p,data_2admin,data2,*
u, alice,data_2admin
```

**Your request(s):**
```go
	roles := e.GetAllNamedRoles("u")
	log.Printf("All roles: %s", roles)
```	
	This returns errors with panic, but when u gets replaced by g, everything works, is there some naming convention that a roles p_type should be g? and why does it need to panic and not return an error instead?

```shell
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x5567b5]


goroutine 1 [running]:
github.com/casbin/casbin/v2/model.Model.HasPolicy(...)
        /home/vijard/go/pkg/mod/github.com/casbin/casbin/v2@v2.60.0/model/policy.go:156
github.com/casbin/casbin/v2/model.Model.HasPolicyEx(0x100c0000b4180?, {0xc0000e4228, 0x1}, {0xc0000e4228, 0x1}, {0xc0000a3510, 0x2, 0x2})
        /home/vijard/go/pkg/mod/github.com/casbin/casbin/v2@v2.60.0/model/policy.go:151 +0x355
github.com/casbin/casbin/v2/persist.LoadPolicyArray({0xc0000a3500?, 0xc0000f19c8?, 0x4cc8bb?}, 0xc0000b4180?)
        /home/vijard/go/pkg/mod/github.com/casbin/casbin/v2@v2.60.0/persist/adapter.go:47 +0x88
github.com/casbin/casbin/v2/persist.LoadPolicyLine({0xc0000e41f8, 0x14}, 0x14?)
        /home/vijard/go/pkg/mod/github.com/casbin/casbin/v2@v2.60.0/persist/adapter.go:40 +0x22c
github.com/casbin/casbin/v2/persist/file-adapter.(*Adapter).loadPolicyFile(0xc0000ada48?, 0xc0000a3290?, 0x709ed8)
        /home/vijard/go/pkg/mod/github.com/casbin/casbin/v2@v2.60.0/persist/file-adapter/adapter.go:98 +0x137
github.com/casbin/casbin/v2/persist/file-adapter.(*Adapter).LoadPolicy(0x6d7600?, 0xc0000a31d0?)
        /home/vijard/go/pkg/mod/github.com/casbin/casbin/v2@v2.60.0/persist/file-adapter/adapter.go:58 +0x59
github.com/casbin/casbin/v2.(*Enforcer).LoadPolicy(0xc000180000)
        /home/vijard/go/pkg/mod/github.com/casbin/casbin/v2@v2.60.0/enforcer.go:316 +0x26b
github.com/casbin/casbin/v2.(*Enforcer).InitWithModelAndAdapter(0xc000180000, 0xc0000a2c00, {0x75ab00?, 0xc0000a09d0?})
        /home/vijard/go/pkg/mod/github.com/casbin/casbin/v2@v2.60.0/enforcer.go:181 +0x2a6
github.com/casbin/casbin/v2.(*Enforcer).InitWithAdapter(0xc000180000, {0x6e248f, 0xc}, {0x75ab00, 0xc0000a09d0})
        /home/vijard/go/pkg/mod/github.com/casbin/casbin/v2@v2.60.0/enforcer.go:158 +0x5c
github.com/casbin/casbin/v2.(*Enforcer).InitWithFile(...)
        /home/vijard/go/pkg/mod/github.com/casbin/casbin/v2@v2.60.0/enforcer.go:148
github.com/casbin/casbin/v2.NewEnforcer({0xc0000f1f50, 0x2, 0xc000034500?})
        /home/vijard/go/pkg/mod/github.com/casbin/casbin/v2@v2.60.0/enforcer.go:102 +0x2da
main.main()
        /home/vijard/Documents/projects/casbin/sandbox/main.go:13 +0x5f
        ```

**Comment by hsluoyz** [comment]
@rajivharlalka "g" is reserved in RBAC, you should not replace it with "u"
