### ISSUE TITLE
[Bug] fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by kooksee** [casbin/casbin#1193]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**Describe the bug**

```
fatal error: concurrent map read and map write

goroutine 2173117 [running]:
runtime.throw({0x1502a6a?, 0x3?})
        /usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc00b2a2fc0 sp=0xc00b2a2f90 pc=0x43ffd1
runtime.mapaccess2_faststr(0x1377e80?, 0x4?, {0xc0058899a0, 0x44})
        /usr/local/go/src/runtime/map_faststr.go:117 +0x3d4 fp=0xc00b2a3028 sp=0xc00b2a2fc0 pc=0x41be94
github.com/casbin/casbin/v2/model.Model.HasPolicy(...)
        /build/vendor/github.com/casbin/casbin/v2/model/policy.go:156
github.com/casbin/casbin/v2.(*Enforcer).addPolicyWithoutNotify(0xc0002644d0, {0x14cda56, 0x1}, {0x14cda56, 0x1}, {0xc00af6de00?, 0x4, 0x4})
        /build/vendor/github.com/casbin/casbin/v2/internal_api.go:43 +0x1b5 fp=0xc00b2a30c0 sp=0xc00b2a3028 pc=0xaf45d5
github.com/casbin/casbin/v2.(*Enforcer).addPolicy(0xc0002644d0, {0x14cda56, 0x1}, {0x14cda56, 0x1}, {0xc00af6de00, 0x4, 0x4})
        /build/vendor/github.com/casbin/casbin/v2/internal_api.go:305 +0x4b fp=0xc00b2a3110 sp=0xc00b2a30c0 pc=0xaf62cb
github.com/casbin/casbin/v2.(*Enforcer).AddNamedPolicy(0xc00b2a3200?, {0x14cda56, 0x1}, {0xc00b2a3210, 0x1, 0xc00b2a3238?})
        /build/vendor/github.com/casbin/casbin/v2/management_api.go:216 +0x10d fp=0xc00b2a31a8 sp=0xc00b2a3110 pc=0xafa1ad
github.com/casbin/casbin/v2.(*Enforcer).AddPolicy(...)
        /build/vendor/github.com/casbin/casbin/v2/management_api.go:200
github.com/casbin/casbin/v2.(*Enforcer).AddPermissionForUser(0xc00b2a32b0?, {0xc00b0182a0, 0x12}, {0xc00b2a3310, 0x3, 0x16c011c?})
        /build/vendor/github.com/casbin/casbin/v2/rbac_api.go:137 +0x1b4 fp=0xc00b2a3248 sp=0xc00b2a31a8 pc=0xafd534
github.com/casbin/casbin/v2.(*SyncedEnforcer).AddPermissionForUser(0xc0001f1950, {0xc00b0182a0, 0x12}, {0xc00b2a3310, 0x3, 0x3})
        /build/vendor/github.com/casbin/casbin/v2/rbac_api_synced.go:99 +0xd4 fp=0xc00b2a32c0 sp=0xc00b2a3248 pc=0xb02294
github.com/turingvideo/cloud-perm/internal/casbin.(*Client).AddOrgRootGroupPerm(0xc0001382a0, {0xc010a64e90, 0x9}, {0xc010a64e9c, 0x4})
        /build/internal/casbin/group.go:216 +0x151 fp=0xc00b2a3350 sp=0xc00b2a32c0 pc=0x10f3d91
github.com/turingvideo/cloud-perm/internal/service/group.(*server).CreateGroup(0xc00035d6c0, {0xc011ff6300?, 0x0?}, 0xc00ae81680)
        /build/internal/service/group/server.go:52 +0x85 fp=0xc00b2a33e0 sp=0xc00b2a3350 pc=0x1186c65
github.com/turingvideo/cloud-perm/pkg/permpb._GroupService_CreateGroup_Handler.func1({0x16d0838, 0xc00b1613b0}, {0x14534c0?, 0xc00ae81680})
        /build/pkg/permpb/group_grpc.pb.go:186 +0x78 fp=0xc00b2a3420 sp=0xc00b2a33e0 pc=0x10dd7b8
github.com/turingvideo/cloud-perm/internal/middlewares.Metric.func1({0x16d0838, 0xc00b1613b0}, {0x14534c0, 0xc00ae81680}, 0xc00b01a520, 0xc00ae0b9f8)
        /build/internal/middlewares/metric.go:39 +0x14a fp=0xc00b2a34c8 sp=0xc00b2a3420 pc=0x118548a
google.golang.org/grpc.chainUnaryInterceptors.func1.1({0x16d0838?, 0xc00b1613b0?}, {0x14534c0?, 0xc00ae81680?})
        /build/vendor/google.golang.org/grpc/server.go:1117 +0x5b fp=0xc00b2a3508 sp=0xc00b2a34c8 pc=0x10c217b
github.com/turingvideo/cloud-perm/internal/middlewares.Logs.func1({0x16d0838, 0xc00b161350}, {0x14534c0, 0xc00ae81680}, 0xc00b01a520, 0xc00af6dd80)
        /build/internal/middlewares/logs.go:98 +0x6d1 fp=0xc00b2a3a18 sp=0xc00b2a3508 pc=0x1184611
google.golang.org/grpc.chainUnaryInterceptors.func1.1({0x16d0838?, 0xc00b161350?}, {0x14534c0?, 0xc00ae81680?})
        /build/vendor/google.golang.org/grpc/server.go:1120 +0x83 fp=0xc00b2a3a58 sp=0xc00b2a3a18 pc=0x10c21a3
google.golang.org/grpc.chainUnaryInterceptors.func1({0x16d0838, 0xc00b161350}, {0x14534c0, 0xc00ae81680}, 0xc00b01a520, 0xc00ae0b9f8)
        /build/vendor/google.golang.org/grpc/server.go:1122 +0x12b fp=0xc00b2a3aa8 sp=0xc00b2a3a58 pc=0x10c20cb
github.com/turingvideo/cloud-perm/pkg/permpb._GroupService_CreateGroup_Handler({0x1407e00?, 0xc00035d6c0}, {0x16d0838, 0xc00b161350}, 0xc00b015f80, 0xc0002ad320)
        /build/pkg/permpb/group_grpc.pb.go:188 +0x138 fp=0xc00b2a3b00 sp=0xc00b2a3aa8 pc=0x10dd678
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003f2380, {0x16d5180, 0xc00c1e4000}, 0xc00a6eaea0, 0xc00ac07a40, 0x203fe60, 0x0)
        /build/vendor/google.golang.org/grpc/server.go:1283 +0xcfd fp=0xc00b2a3e48 sp=0xc00b2a3b00 pc=0x10c2efd
google.golang.org/grpc.(*Server).handleStream(0xc0003f2380, {0x16d5180, 0xc00c1e4000}, 0xc00a6eaea0, 0x0)
        /build/vendor/google.golang.org/grpc/server.go:1620 +0xa1b fp=0xc00b2a3f68 sp=0xc00b2a3e48 pc=0x10c755b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /build/vendor/google.golang.org/grpc/server.go:922 +0x98 fp=0xc00b2a3fe0 sp=0xc00b2a3f68 pc=0x10c0a58
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc00b2a3fe8 sp=0xc00b2a3fe0 pc=0x46fc81
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /build/vendor/google.golang.org/grpc/server.go:920 +0x28a
```

**To Reproduce**
- enable casbin watcher
- Deploy two replica instances
- Concurrent read and write data
- I use SyncedEnforcer, but I finally found that SyncedEnforcer does not use locks on the following methods
```
        SelfAddPolicy(sec string, ptype string, rule []string) (bool, error)
	SelfAddPolicies(sec string, ptype string, rules [][]string) (bool, error)
	SelfRemovePolicy(sec string, ptype string, rule []string) (bool, error)
	SelfRemovePolicies(sec string, ptype string, rules [][]string) (bool, error)
	SelfRemoveFilteredPolicy(sec string, ptype string, fieldIndex int, fieldValues ...string) (bool, error)
	SelfUpdatePolicy(sec string, ptype string, oldRule, newRule []string) (bool, error)
	SelfUpdatePolicies(sec string, ptype string, oldRules, newRules [][]string) (bool, error)
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hsluoyz** [comment]
@PokIsemaine
