### ISSUE TITLE
[Bug] Whenever I use the GetRolesForUser method, I always receive an error stating "invalid memory address or nil pointer dereference."

### ISSUE THREAD

**Issue by MichealJl** [casbin/casbin#1345]
version : v2.79.0

model
```
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _, (_, _)

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act
```

policy.csv
```
p, alice, data1, read
p, data2_admin, data2, write
p, data3_admin, data3, read
p, data4_admin, data4, write
p, data5_admin, data5, read
p, data6_admin, data6, write
p, data7_admin, data7, read
p, data8_admin, data8, write

g, alice, data2_admin, 0000-01-01 00:00:00, 0000-01-02 00:00:00
g, alice, data3_admin, 0000-01-01 00:00:00, 9999-12-30 00:00:00
g, alice, data4_admin, _, _
g, alice, data5_admin, _, 9999-12-30 00:00:00
g, alice, data6_admin, _, 0000-01-02 00:00:00
g, alice, data7_admin, 0000-01-01 00:00:00, _
g, alice, data8_admin, 9999-12-30 00:00:00, _
```

code

```go
func Test() {
	en, er := casbin.NewEnforcer("./casbingo/model.conf", "./casbingo/policy.csv")
	if er != nil {
		panic(errors.Wrap(er, "NewEnforcer"))
	}
	fmt.Println(en.GetRolesForUser("alice"))
}
```

result

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x58 pc=0x1002da604]

goroutine 1 [running]:
github.com/casbin/casbin/v2.(*Enforcer).GetRolesForUser(...)
        /Users/xxx/go/pkg/mod/github.com/casbin/casbin/v2@v2.79.0/rbac_api.go:27
gitea.drugeyes.vip/test/casbingo.Test()
        /Users/xxxx/go/src/gitea.drugeyes.vip/test/casbingo/test2.go:14 +0xa4
main.main()
        /Users/test/main.go:22 +0x1c
```

**Comment by hsluoyz** [comment]
@MichealJl why close?

**Comment by MichealJl** [comment]
@hsluoyz  

I solved it using the following method

```
e.SetRoleManager(defaultrolemanager.NewRoleManager(10))
_ = e.BuildRoleLinks()
```

**Comment by osmian** [comment]
@MichealJl curious on this, why the role manager is not initialized by default here?

**Comment by hsluoyz** [comment]
@osmian the `NewEnforcer()` API should already have initialized the role manager. Can you check the code and recent git commits?

**Comment by osmian** [comment]
> @osmian the `NewEnforcer()` API should already have initialized the role manager. Can you check the code and recent git commits?

@hsluoyz  looks like the code to init the role manager map was changed a few months back in this MR
- https://github.com/casbin/casbin/pull/1294/files#diff-52fa32ffe98987501702e518f1b8ed9404f47f96bc246daa564bcfac253cd88bR472-R486

The initialization `initRmMap` with the given code, falls into the code here and initializes a conditional role manager but not a role manager.
- https://github.com/casbin/casbin/blob/master/enforcer.go#L476-L478

I'm not too familiar with this conditional role manager vs default role manager but that would explain why the role manager is nil here
