### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Garagator3000** [casbin/casbin#1468]
https://github.com/casbin/casbin/issues/888
This error apparently has not been fixed.

There was already an issue opened about this, but it was closed in version 2.37.1

go 1.22.4
github.com/casbin/casbin/v2 v2.71.1

This error was seen twice on the project.
Unfortunately, panics from sync.Mutex cannot be caught via recover().

```
...
goroutine 104658 [running]:
sync.fatal({0x10f316c?, 0xf92de0?})
	/usr/local/go/src/runtime/panic.go:1007 +0x18
sync.(*Mutex).unlockSlow(0xc00039e248, 0xffffffff)
	/usr/local/go/src/sync/mutex.go:229 +0x35
sync.(*Mutex).Unlock(...)
	/usr/local/go/src/sync/mutex.go:223
sync.(*Map).Swap(0xc00039e248, {0xee7f40, 0xc0009786d0}, {0x1039740, 0xc000ba0870})
	/usr/local/go/src/sync/map.go:367 +0x35c
sync.(*Map).Store(...)
	/usr/local/go/src/sync/map.go:155
github.com/casbin/casbin/v2.(*Enforcer).getAndStoreMatcherExpression(0x0?, 0x0, {0xc000353600, 0x75}, 0xc00092cf90)
	/go/pkg/mod/github.com/casbin/casbin/v2@v2.71.1/enforcer.go:726 +0xb9
github.com/casbin/casbin/v2.(*Enforcer).enforce(0xc00039e1e0, {0x0, 0x0}, 0x0, {0xc00092cf30, 0x3, 0x3})
	/go/pkg/mod/github.com/casbin/casbin/v2@v2.71.1/enforcer.go:579 +0x9e5
github.com/casbin/casbin/v2.(*Enforcer).Enforce(...)
	/go/pkg/mod/github.com/casbin/casbin/v2@v2.71.1/enforcer.go:733
{PRIVATE}/usecases/permission.(*Usecase).CheckPolicy(0xc000820e10, {0x1e?, 0xc0011681b0?}, {0x131d7a8, 0xc00093bad0})
	/go/src/app/internal/app/a5/usecases/permission/usecase.go:168 +0x5ac
...
```

**Comment by Garagator3000** [comment]
Could the problem be that multiple people are simultaneously performing actions on behalf of the same user?

**Comment by hsluoyz** [comment]
@Garagator3000 there's mutex, why panic?

**Comment by alexvelfr** [comment]
```fatal error: sync: unlock of unlocked mutex
goroutine 548800025 [running]:
sync.fatal({0x2ab71b6?, 0x264a660?})
        /usr/local/go/src/runtime/panic.go:1031 +0x18
sync.(*Mutex).unlockSlow(0xc000d863e0, 0xffffffff)
        /usr/local/go/src/sync/mutex.go:231 +0x35
sync.(*Mutex).Unlock(...)
        /usr/local/go/src/sync/mutex.go:225
sync.(*Map).Swap(0xc000d863e0, {0x2449040, 0xc005c8abd0}, {0x284fa40, 0xc007fa4cd0})
        /usr/local/go/src/sync/map.go:391 +0x35c
sync.(*Map).Store(...)
        /usr/local/go/src/sync/map.go:158
github.com/casbin/casbin/v2.(*Enforcer).getAndStoreMatcherExpression(0x0?, 0x0, {0xc001100800, 0x33}, 0xc00ecaf260)
        /.go/pkg/mod/github.com/casbin/casbin/v2@v2.87.1/enforcer.go:825 +0xb9
github.com/casbin/casbin/v2.(*Enforcer).enforce(0xc000d86370, {0x0, 0x0}, 0x0, {0xc00ecaf230, 0x3, 0x3})
        /.go/pkg/mod/github.com/casbin/casbin/v2@v2.87.1/enforcer.go:679 +0xb05
github.com/casbin/casbin/v2.(*Enforcer).Enforce(...)
        /.go/pkg/mod/github.com/casbin/casbin/v2@v2.87.1/enforcer.go:832
...../services.(*roleModule).CheckPermission(_, {_, _}, {0xce, 0x0, {0xc00c9ab9f0, 0xf}, {0xc000ab0390, 0x5, 0x5}, ...}, ...)
```

have the same problem on version v2.87.1

**Comment by hsluoyz** [comment]
@alexvelfr use latest version. We only support the latest version

**Comment by randomAnalyst** [comment]
@hsluoyz we are still getting this concurrent map read and map write issue for AddGroupingPolicy and RemoveGroupingPolicy the latest casbin version v2.108.0.
This is blocking us from concurrency tests.

fatal error: concurrent map read and map write

goroutine 9413 gp=0xc01732b6c0 m=106 mp=0xc000980008 [running]:
runtime.fatal({0x6f52fe6, 0x21})
	/home/go/go/src/runtime/panic.go:1123 +0x5c fp=0xc0069080c0 sp=0xc006908090 pc=0x24582bc
internal/runtime/maps.fatal({0x6f52fe6?, 0xc006908150?})
	/home/go/go/src/runtime/panic.go:1058 +0x18 fp=0xc0069080e0 sp=0xc0069080c0 pc=0x2492bf8
runtime.mapaccess2_faststr(0xc00e180060?, 0x75f2050?, {0xc0001f5980?, 0x75e5bd8?})
	/home/go/go/src/internal/runtime/maps/runtime_faststr_swiss.go:174 +0x117 fp=0xc006908160 sp=0xc0069080e0 pc=0x241f6d7
github.com/casbin/casbin/v2/model.Model.HasPolicy(0xc000962870, {0x75f2050, 0x1}, {0x75f2050, 0x1}, {0xc00e180060, 0x3, 0x3})
	/root/go/pkg/mod/github.com/casbin/casbin/v2@v2.103.0/model/policy.go:203 +0xd0 fp=0xc0069081a8 sp=0xc006908160 pc=0x5823550
github.com/casbin/casbin/v2.(*Enforcer).addPolicyWithoutNotify(0xc00117c0c0, {0x75f2050, 0x1}, {0x75f2050, 0x1}, {0xc00e180060, 0x3, 0x3})
	/root/go/pkg/mod/github.com/casbin/casbin/v2@v2.103.0/internal_api.go:43 +0x115 fp=0xc006908230 sp=0xc0069081a8 pc=0x5844315
github.com/casbin/casbin/v2.(*Enforcer).addPolicy(0xc00117c0c0, {0x75f2050, 0x1}, {0x75f2050, 0x1}, {0xc00e180060, 0x3, 0x3})
	/root/go/pkg/mod/github.com/casbin/casbin/v2@v2.103.0/internal_api.go:332 +0x48 fp=0xc006908288 sp=0xc006908230 pc=0x58466a8
github.com/casbin/casbin/v2.(*Enforcer).AddNamedGroupingPolicy(0xc006908360?, {0x75f2050?, 0xc00008620f?}, {0xc0069085c8?, 0x6ec8980?, 0x6?})
	/root/go/pkg/mod/github.com/casbin/casbin/v2@v2.103.0/management_api.go:378 +0x85 fp=0xc0069082f8 sp=0xc006908288 pc=0x584a585
github.com/casbin/casbin/v2.(*Enforcer).AddGroupingPolicy(...)
	/root/go/pkg/mod/github.com/casbin/casbin/v2@v2.103.0/management_api.go:354
github.com/casbin/casbin/v2.(*SyncedEnforcer).AddGroupingPolicy(0xc000962f90, {0xc0069085c8, 0x1, 0x1})
	/root/go/pkg/mod/github.com/casbin/casbin/v2@v2.103.0/enforcer_synced.go:483 +0xac fp=0xc006908370 sp=0xc0069082f8 pc=0x584138c
github.ibm.com/lakehouse/ibm-lh-cpg/pkg/authorization.PutOwnerMsgToEnforcerForMilvus({{0xc000084022, 0x9}, {0xc0319111c0, 0x10}, {0x6ecd3eb, 0x7}, {0xc020c22649, 0x7}, {0x0, 0x0}, ...})
