### ISSUE TITLE
Error in TestABACModel

### ISSUE THREAD

**Issue by Shamil-R** [casbin/casbin#150]
Hello there.
I run test in package and get result in terminal like

```
--- FAIL: TestABACModel (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x517cc2]

goroutine 65 [running]:
testing.tRunner.func1(0xc42041ad20)
	/usr/local/go/src/testing/testing.go:742 +0x29d
panic(0x564700, 0x66ba30)
	/usr/local/go/src/runtime/panic.go:502 +0x229
*/platform/vendor/github.com/casbin/casbin.(*Enforcer).Enforce(0xc4203b5260, 0xc42005dda8, 0x3, 0x3, 0x40f9e9)
	*/platform/vendor/github.com/casbin/casbin/enforcer.go:387 +0x1322
*/platform/vendor/github.com/casbin/casbin.testEnforce(0xc42041ad20, 0xc4203b5260, 0x592832, 0x5, 0x56c540, 0xc4203b2a00, 0x5926e2, 0x4, 0x623001)
	*/platform/vendor/github.com/casbin/casbin/model_test.go:26 +0x13d
*/platform/vendor/github.com/casbin/casbin.TestABACModel(0xc42041ad20)
	*/platform/vendor/github.com/casbin/casbin/model_test.go:340 +0x12d
testing.tRunner(0xc42041ad20, 0x59d390)
	/usr/local/go/src/testing/testing.go:777 +0xd0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:824 +0x2e0
```

It's my fail or what?

**Comment by hsluoyz** [comment]
My local test runs well:

```
=== RUN   TestABACModel
2018/10/18 13:49:28 Model:
2018/10/18 13:49:28 r.r: sub, obj, act
2018/10/18 13:49:28 p.p: sub, obj, act
2018/10/18 13:49:28 e.e: some(where (p_eft == allow))
2018/10/18 13:49:28 m.m: r_sub == r_obj.Owner
2018/10/18 13:49:28 Request: alice, {data1 alice}, read ---> true
2018/10/18 13:49:28 Request: alice, {data1 alice}, write ---> true
2018/10/18 13:49:28 Request: alice, {data2 bob}, read ---> false
2018/10/18 13:49:28 Request: alice, {data2 bob}, write ---> false
2018/10/18 13:49:28 Request: bob, {data1 alice}, read ---> false
2018/10/18 13:49:28 Request: bob, {data1 alice}, write ---> false
2018/10/18 13:49:28 Request: bob, {data2 bob}, read ---> true
2018/10/18 13:49:28 Request: bob, {data2 bob}, write ---> true
--- PASS: TestABACModel (0.00s)
PASS
```

And you can also see the Travis CI passes well: https://travis-ci.org/casbin/casbin

So I think it's an issue of your side. Please use latest Golang 1.11 and pull the latest source code.

**Comment by Shamil-R** [comment]
I update golang to 1.11 dut same result.
Can you show your Gopkg.lock?

**Comment by Shamil-R** [comment]
In my project version of https://github.com/Knetic/govaluate is 3.0.0. 
Error raise in Knetic/govaluate package, when 
```func readToken(stream *lexerStream, state lexerState, functions map[string]ExpressionFunction) (ExpressionToken, error, bool) {}```
try parse '.' abac_model.conf in 
```
[matchers]
m = r.sub == r.obj.Owner
```
between obj and Owner

**Comment by hsluoyz** [comment]
``3.0.0`` is too old, you should use the head of the master branch.

**Comment by Shamil-R** [comment]
It's work!
Many thank you!
