### ISSUE TITLE
Panic in `role_definition` with g1

### ISSUE THREAD

**Issue by PeerXu** [casbin/casbin#155]
Hi, everyone.

When I follow the tutorial to try rbac with resource([model](https://github.com/casbin/casbin/blob/master/examples/rbac_with_resource_roles_model.conf), [policy](https://github.com/casbin/casbin/blob/master/examples/rbac_with_resource_roles_policy.csv)) example.

There is my program:

```
package main

import (
	"os"

	"github.com/casbin/casbin"
)

func main() {
	root := os.Getenv("GOPATH")
	conf := root + "/src/github.com/casbin/casbin/examples/rbac_with_resource_roles_model.conf"
	policy := root + "/src/github.com/casbin/casbin/examples/rbac_with_resource_roles_policy.csv"
	e := casbin.NewEnforcer(conf, policy)

	println(e.Enforce("alice", "data1", "read"))
}
```

Everything all right when I follow the guide.

But, when I change g2 to g1, the program panic.

```
# rbac_with_resource_roles_model.conf

[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _
g1 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && g1(r.obj, p.obj) && r.act == p.act
```

```
# rbac_with_resource_roles_policy.csv

p, alice, data1, read
p, bob, data2, write
p, data_group_admin, data_group, write

g, alice, data_group_admin
g1, data1, data_group
g1, data2, data_group
```

Exception:

```
2018/10/25 08:54:06 Model:
2018/10/25 08:54:06 e.e: some(where (p_eft == allow))
2018/10/25 08:54:06 m.m: g(r_sub, p_sub) && g1(r_obj, p_obj) && r_act == p_act
2018/10/25 08:54:06 g.g: _, _
2018/10/25 08:54:06 r.r: sub, obj, act
2018/10/25 08:54:06 p.p: sub, obj, act
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x11094d5]

goroutine 1 [running]:
github.com/casbin/casbin/persist.LoadPolicyLine(0xc4200d4260, 0x15, 0xc4200aa870)
	/Users/peer/.golang/src/github.com/casbin/casbin/persist/adapter.go:37 +0x125
github.com/casbin/casbin/persist/file-adapter.(*Adapter).loadPolicyFile(0xc4200a6440, 0xc4200aa870, 0x116c780, 0x0, 0x0)
	/Users/peer/.golang/src/github.com/casbin/casbin/persist/file-adapter/adapter.go:86 +0x14c
github.com/casbin/casbin/persist/file-adapter.(*Adapter).LoadPolicy(0xc4200a6440, 0xc4200aa870, 0xc4200aac01, 0x124e7d0)
	/Users/peer/.golang/src/github.com/casbin/casbin/persist/file-adapter/adapter.go:46 +0xa8
github.com/casbin/casbin.(*Enforcer).LoadPolicy(0xc4200d6000, 0x124e7d0, 0x1163f52)
	/Users/peer/.golang/src/github.com/casbin/casbin/enforcer.go:212 +0x53
github.com/casbin/casbin.(*Enforcer).InitWithModelAndAdapter(0xc4200d6000, 0xc4200aa870, 0x117eb40, 0xc4200a6440)
	/Users/peer/.golang/src/github.com/casbin/casbin/enforcer.go:126 +0x2a1
github.com/casbin/casbin.(*Enforcer).InitWithAdapter(0xc4200d6000, 0xc42009c120, 0x5d, 0x117eb40, 0xc4200a6440)
	/Users/peer/.golang/src/github.com/casbin/casbin/enforcer.go:109 +0xa0
github.com/casbin/casbin.(*Enforcer).InitWithFile(0xc4200d6000, 0xc42009c120, 0x5d, 0xc42009c180, 0x5d)
	/Users/peer/.golang/src/github.com/casbin/casbin/enforcer.go:103 +0x84
github.com/casbin/casbin.NewEnforcer(0xc420069f28, 0x2, 0x2, 0xc4200a6430)
	/Users/peer/.golang/src/github.com/casbin/casbin/enforcer.go:72 +0x187
main.main()
	/tmp/test/main.go:13 +0x198
exit status 2
```

**Comment by hsluoyz** [comment]
Casbin loads the ``g`` policy rules in the order of ``g``, ``g2``, ``g3``, ``g4``, ``g5``, see below code. You must name your different RBAC systems in this way. So your second RBAC system should be ``g2``.

https://github.com/casbin/casbin/blob/c96868ecc4e0abd15af3b349d58fa663c63aa25f/model/model.go#L80-L89

Of course, it's not bad to support arbitrary names. PR to improve it is welcom.
