### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by guobingithub** [casbin/casbin#205]
when i use casbin.Enforcer.Enforce(xxsub,xxobj,xxact), a panic occurred!! 

panic log is below:
```
 | panic: runtime error: index out of range
 |
 | goroutine 271 [running]:
 | /authority-manager/vendor/github.com/casbin/casbin.(*Enforcer).Enforce(0xc0001c9e30, 0xc0003ffab8, 0x3, 0x3, 0x2)
 |      /authority-manager/vendor/github.com/casbin/casbin/enforcer.go:348 +0x174d
 | /authority-manager/auth.(*RbacService).Enforce(0xfc04d0, 0xb49120, 0xc000184f30, 0xc000255280, 0xfc04d0, 0xc000184e70, 0x9e9ee0)
 |      /authority-manager/auth/auth.go:505 +0x2b8
 | /authority-manager/proto._RbacService_Enforce_Handler(0xa6bb40, 0xfc04d0, 0xb49120, 0xc000184f30, 0xc00029ce00, 0x0, 0x0, 0x0, 0x8, 0x0)
 |      /authority-manager/proto/rbac.pb.go:3034 +0x23e
 | /vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc000234300, 0xb4bfc0, 0xc000345200, 0xc00036c700, 0xc000242240, 0xf98108, 0x0, 0x0, 0x0)
 |      /vendor/google.golang.org/grpc/server.go:982 +0x4cd
 | /vendor/google.golang.org/grpc.(*Server).handleStream(0xc000234300, 0xb4bfc0, 0xc000345200, 0xc00036c700, 0x0)
 |      /vendor/google.golang.org/grpc/server.go:1208 +0x1311
 | /vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000026e74, 0xc000234300, 0xb4bfc0, 0xc000345200, 0xc00036c700)
 |      /vendor/google.golang.org/grpc/server.go:686 +0x9f
 | created by /vendor/google.golang.org/grpc.(*Server).serveStreams.func1
 |      /vendor/google.golang.org/grpc/server.go:684 +0xa1
 | exit status 2
```

**Comment by guobingithub** [comment]
anyone meet the same case like me??

**Comment by rbastic** [comment]
Can you paste a full code example that reproduces the problem?

**Comment by erichulburd** [comment]
Related: https://github.com/casbin/casbin/issues/228
