### ISSUE TITLE
Any document for migrating from v1.x?

### ISSUE THREAD

**Issue by zinwalin** [casbin/casbin#312]
Is old function EnforceSafe replaced with new one HasPermissionForUser?

**Comment by hsluoyz** [comment]
See: https://github.com/casbin/gorm-adapter/commit/32167fbff7462b95b8ec1504d20b348ee7b3f6ff

**Comment by zinwalin** [comment]
Is old function EnforceSafe replaced with new one HasPermissionForUser?

**Comment by hsluoyz** [comment]
In Casbin 2.x, `Enforce()` already returns error, it replaced `EnforceSafe()`.

**Comment by neelofer-appdirect** [comment]
We are using Casbin 2.1.2 but I still see a panic and cannot find xxxSafe functions anywhere in the Casbin library. How do we havve Cabsin return error instead of panic? Document shared in [comment above](https://github.com/casbin/casbin/issues/312#issuecomment-544210143) seems outdated maybe?

**Comment by hsluoyz** [comment]
@neelofer-appdirect can you post the panic log? Which line causes panic?

**Comment by neelofer-appdirect** [comment]
```2020/01/06 10:59:50 printing enforcer .. &{model.conf map[e:map[e:0xc0000ae660] m:map[m:0xc0000ae780] p:map[p:0xc0000ae5a0] r:map[r:0xc0000ae4e0]] map[ipMatch:0x128d0e0 keyMatch:0x128b710 keyMatch2:0x128bb00 keyMatch3:0x128bef0 keyMatch4:0x128cb80 regexMatch:0x128cd20] 0x194d538 0xc0000962f0 <nil> 0xc0001563a0 true true true}
panic: error parsing regexp: missing argument to repetition operator: `*` [recovered]
panic: error parsing regexp: missing argument to repetition operator: `*`

goroutine 50 [running]:
testing.tRunner.func1(0xc000184500)
/usr/local/Cellar/go/1.12/libexec/src/testing/testing.go:830 +0x68a
panic(0x153f840, 0xc0004ec4c0)
/usr/local/Cellar/go/1.12/libexec/src/runtime/panic.go:522 +0x1b5
github.com/casbin/casbin/v2/util.RegexMatch(...)
/~path/tools/golang/pkg/mod/github.com/casbin/casbin/v2@v2.1.2/util/builtin_operators.go:171
github.com/casbin/casbin/v2/util.KeyMatch2(0x15aa0c1, 0x1c, 0xc0000d22bc, 0x19, 0x194d2c0)
/~path/tools/golang/pkg/mod/github.com/casbin/casbin/v2@v2.1.2/util/builtin_operators.go:63 +0x23a
github.com/casbin/casbin/v2/util.KeyMatch2Func(0xc0004ec420, 0x2, 0x2, 0x93, 0xc0002faee0, 0xc0002fedb0, 0x10970e2)
/~path/tools/golang/pkg/mod/github.com/casbin/casbin/v2@v2.1.2/util/builtin_operators.go:71 +0x105
github.com/Knetic/govaluate.makeFunctionStage.func1(0x0, 0x0, 0x151b7c0, 0xc0004ec440, 0x1636f80, 0xc0004e8170, 0x0, 0x0, 0x93, 0xc00030afa0)
/~path/tools/golang/pkg/mod/github.com/!knetic/govaluate@v3.0.1-0.20171022003610-9aa49832a739+incompatible/evaluationStage.go:243 +0xe1
github.com/Knetic/govaluate.EvaluableExpression.evaluateStage(0x15ac58e, 0x22, 0x1, 0xc0003d0c00, 0x22, 0x40, 0xc00030b450, 0xc000154140, 0x93, 0xc00030aff0, ...)
/~path/tools/golang/pkg/mod/github.com/!knetic/govaluate@v3.0.1-0.20171022003610-9aa49832a739+incompatible/EvaluableExpression.go:232 +0x1b7
github.com/Knetic/govaluate.EvaluableExpression.evaluateStage(0x15ac58e, 0x22, 0x1, 0xc0003d0c00, 0x22, 0x40, 0xc00030b450, 0xc000154140, 0x93, 0xc00030b3b0, ...)
/~path/tools/golang/pkg/mod/github.com/!knetic/govaluate@v3.0.1-0.20171022003610-9aa49832a739+incompatible/EvaluableExpression.go:205 +0x78b
github.com/Knetic/govaluate.EvaluableExpression.evaluateStage(0x15ac58e, 0x22, 0x1, 0xc0003d0c00, 0x22, 0x40, 0xc00030b450, 0xc000154140, 0x93, 0xc00030b400, ...)
/~path/tools/golang/pkg/mod/github.com/!knetic/govaluate@v3.0.1-0.20171022003610-9aa49832a739+incompatible/EvaluableExpression.go:172 +0xbc1
github.com/Knetic/govaluate.EvaluableExpression.evaluateStage(0x15ac58e, 0x22, 0x1, 0xc0003d0c00, 0x22, 0x40, 0xc00030b450, 0xc000154140, 0x93, 0xc00030b450, ...)
/~path/tools/golang/pkg/mod/github.com/!knetic/govaluate@v3.0.1-0.20171022003610-9aa49832a739+incompatible/EvaluableExpression.go:172 +0xbc1
github.com/Knetic/govaluate.EvaluableExpression.Eval(0x15ac58e, 0x22, 0x1, 0xc0003d0c00, 0x22, 0x40, 0xc00030b450, 0xc000154140, 0x93, 0x1637a00, ...)
/~path/tools/golang/pkg/mod/github.com/!knetic/govaluate@v3.0.1-0.20171022003610-9aa49832a739+incompatible/EvaluableExpression.go:163 +0x115
github.com/casbin/casbin/v2.(*Enforcer).enforce(0xc000158700, 0x0, 0x0, 0xc00030aaf0, 0x5, 0x5, 0xc00046e6d8, 0x1044818, 0x50)
/~path/tools/golang/pkg/mod/github.com/casbin/casbin/v2@v2.1.2/enforcer.go:406 +0x1282
github.com/casbin/casbin/v2.(*Enforcer).Enforce(0xc000158700, 0xc00030aaf0, 0x5, 0x5, 0x5e12c5ce, 0xc00046e760, 0x10bb597)
/~path/tools/golang/pkg/mod/github.com/casbin/casbin/v2@v2.1.2/enforcer.go:495 +0x69
github.com/AppDirect/AppConfigr/pkg/rbac.TestCasbinEnforcerPolicies.func13(0xc000184500)
/~path/tools/~path/temp_test.go:194 +0x1d7
testing.tRunner(0xc000184500, 0xc0002cff00)
/usr/local/Cellar/go/1.12/libexec/src/testing/testing.go:865 +0x164
created by testing.(*T).Run
/usr/local/Cellar/go/1.12/libexec/src/testing/testing.go:916 +0x69a
```

**Comment by hsluoyz** [comment]
It seems that your regex passed to `RegexMatch()` is in wrong format. We didn't return it as an error because we think your model should be 100% provided by yourself and correct.

**Comment by neelofer-appdirect** [comment]
Actually our use case is that users might add policies at runtime which should not break the application. Is there a validation / verification of policies that we can instead do before a policy is added?

**Comment by hsluoyz** [comment]
The error is obvious, see: https://casbin.org/docs/en/function. "*" is not valid in `keyMatch2()`. 

The policy can be validated on front-end, see our online-editor: https://casbin.org/en/editor . It runs all code on browser-side, so it will be the first check for your end-user's custom policy.

For Go backend, Casbin's `enforce()` should catch and recover from the panic and return an error instead. Can you help make a PR with it?

**Comment by neelofer-appdirect** [comment]
Ok will create one and let you know. Thank you.

**Comment by hsluoyz** [comment]
Merged.
