### ISSUE TITLE
GetAllRoles gets nil pointer 

### ISSUE THREAD

**Issue by lominskyi-perfectial** [casbin/casbin#502]
```
enforcer, err := casbin.NewEnforcer("model.conf", "policy.csv")
if err != nil {
	return Middleware{}, fmt.Errorf("failed to to get model/policy for casbin enforcer due to %w", err)
	}
fmt.Println(enforcer.GetAllRoles())
```

#policy.csv
```
p, Admin, /api/v1/users, GET
p, Guest, /api/v1/users, GET
```

#conf.model
```
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.sub == p.sub && r.obj == p.obj && r.act == p.act
```

#Result
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1510569]

goroutine 1 [running]:
github.com/casbin/casbin/v2/model.Model.GetValuesForFieldInPolicy(0xc00010a930, 0x18a1dc9, 0x1, 0x18a1dce, 0x1, 0x1, 0x19bb8e0, 0xc00014a6e0, 0xc0000392d0)
	/go/pkg/mod/github.com/casbin/casbin/v2@v2.0.0/model/policy.go:144 +0xb9
github.com/casbin/casbin/v2.(*Enforcer).GetAllNamedRoles(...)
	/go/pkg/mod/github.com/casbin/casbin/v2@v2.0.0/management_api.go:54
pkg.NewMiddleware(0xc0000a8bc0, 0x40, 0x3, 0x0, 0x0, 0xc00007e180, 0xc000000180)
```

Is there anything I can do? I use: github.com/casbin/casbin/v2
Thanks!

**Comment by dovics** [comment]
@lominskyi-perfectial I think you should update to the lastest version, you are still using 2.0.0

**Comment by lominskyi-perfectial** [comment]
@dovics updated to 2.7.2. Get the empty array now.
Gonna read the doc, I might miss something sufficient
