### ISSUE TITLE
Problem with ABAC?

### ISSUE THREAD

**Issue by danedmunds** [casbin/casbin#55]
I'm trying to use ABAC and I'm getting a panic

I'm using the example ABAC model
```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.sub == r.obj.Owner
```

I have a simple test
```go
package main

import (
	"fmt"
	"testing"

	"github.com/casbin/casbin"
	"github.com/govaluate"
)

type Blah struct {
	Owner string
}

func TestCasbin(t *testing.T) {
	enforcer := casbin.NewEnforcer("./abac_model.conf")
	res := enforcer.Enforce("one", Blah{Owner: "one"}, "two")
	fmt.Println(res)
}
```

I get the following...
```
Running tool: /usr/local/bin/go test -timeout 30s github.com/danedmunds/myrepo -run ^TestCasbin$

2017/12/07 13:56:36 [Model:]
2017/12/07 13:56:36 r.r: sub, obj, act
2017/12/07 13:56:36 p.p: sub, obj, act
2017/12/07 13:56:36 e.e: some(where (p_eft == allow))
2017/12/07 13:56:36 m.m: r_sub == r_obj.Owner
--- FAIL: TestCasbin (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12bee1c]

goroutine 6 [running]:
testing.tRunner.func1(0xc420104270)
	/usr/local/Cellar/go/1.8/libexec/src/testing/testing.go:622 +0x29d
panic(0x132a500, 0x1517850)
	/usr/local/Cellar/go/1.8/libexec/src/runtime/panic.go:489 +0x2cf
github.com/danedmunds/myrepo/vendor/github.com/casbin/casbin.(*Enforcer).Enforce(0xc420018960, 0xc420055f68, 0x3, 0x3, 0x0)
	/Users/ddm/go/src/github.com/danedmunds/myrepo/vendor/github.com/casbin/casbin/enforcer.go:361 +0x165c
github.com/danedmunds/myrepo.TestCasbin(0xc420104270)
	/Users/ddm/go/src/github.com/danedmunds/myrepo/access_test.go:28 +0x202
testing.tRunner(0xc420104270, 0x13931e0)
	/usr/local/Cellar/go/1.8/libexec/src/testing/testing.go:657 +0x96
created by testing.(*T).Run
	/usr/local/Cellar/go/1.8/libexec/src/testing/testing.go:697 +0x2ca
FAIL	github.com/danedmunds/myrepo	0.012s
Error: Tests failed.
```

I've traced it down to govaluate returning the error `Unable to parse numeric value '.' to float64` when the expression is parsed.

What's strange is that the following  test passes without any issue
```go
func TestGovaluate(t *testing.T) {
	exp, err := govaluate.NewEvaluableExpressionWithFunctions("r_sub == r_obj.Owner", nil)
	fmt.Println(err)
	res, err := exp.Evaluate(map[string]interface{}{
		"r_sub": "one",
		"r_obj": Subject{Blah: "one"},
	})
	fmt.Println(err)
	fmt.Println(res)
}
```

Have I made a mistake in my configuration of casbin? Am I hitting a conflict between casbin/govaluate?

I'm using glide to vendor both of these dependencies...
```yml
- package: github.com/casbin/casbin
  version: ^1.2.0
- package: github.com/Knetic/govaluate
  version: ^3.0.0
```

lock file...
```yml
- name: github.com/casbin/casbin
  version: 3b25a82bd1e3ce20dd037ba7ecb06140bd9acc5c
  subpackages:
  - config
  - file-adapter
  - model
  - persist
  - rbac
  - util
- name: github.com/Knetic/govaluate
  version: d216395917cc49052c7c7094cf57f09657ca08a8
```

Any help would be greatly appreciated! Thanks!

**Comment by hsluoyz** [comment]
There's a similar issue here: https://github.com/Knetic/govaluate/issues/61. And the author seems to have fixed it. Do not use govaluate's ``3.0.0`` release. It is very old. You can use its latest commit in your glide.

**Comment by danedmunds** [comment]
That fixed my problem!
Moved to the absolute latest govaluate commit
