### ISSUE TITLE
panic: interface conversion: *beegoormadapter.Adapter is not persist.Adapter: missing method LoadPolicy

### ISSUE THREAD

**Issue by smp12345** [casbin/casbin#687]
**What's your scenario? What do you want to achieve?**
```
When I use the Beego ORM adapter, refer to the GitHub sample code and report the following error
```
**Your model:**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act,eft

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow)) && !some(where (p.eft == deny))

[matchers]
m = g(r.sub, p.sub) && my_func(r.obj, p.obj) && r.act == p.act
```

**Your policy:**

```
"alice", "data1", "read"
```

**test code**
```
func main() {
	// Initialize a Beego ORM adapter and use it in a Casbin enforcer:
	a := beegoormadapter.NewAdapter( "mysql", "root:xxxx@tcp(127.0.0.1:3306)/casbin",true) // Your driver and data source.

	e, err := casbin.NewEnforcer("model.conf", a)
	if err != nil {
		log.Fatalln(err)
	}
	// Check the permission.
	e.Enforce("alice", "data1", "read")

	// Modify the policy.
	// e.AddPolicy(...)
	// e.RemovePolicy(...)

	// Save the policy back to DB.
	e.SavePolicy()
}
```

**Frame error:**

```
panic: interface conversion: *beegoormadapter.Adapter is not persist.Adapter: missing method LoadPolicy

goroutine 1 [running]:
github.com/casbin/casbin/v2.NewEnforcer(0xc0000c9f58, 0x2, 0x2, 0x29, 0xc0000c9f3f, 0x1)
        D:/gopath/go/pkg/mod/github.com/casbin/casbin/v2@v2.20.2/enforcer.go:94 +0x234
main.main()
        D:/go-project/ec/test/test.go:15 +0xee

```

**Comment by nodece** [comment]
are you using `beegoormadapter "github.com/casbin/beego-orm-adapter/v2"`?

**Comment by smp12345** [comment]
That's done, thank you

**Comment by hsluoyz** [comment]
README fixed: https://github.com/casbin/beego-orm-adapter/commit/a77df7a82a4d6071ade069992033484ff406001c
