### ISSUE TITLE
[Bug]    Concurrency add user authorization   fatal error: concurrent map writes

### ISSUE THREAD

**Issue by dollarkillerx** [casbin/casbin#830]
casbin version:  2021-07-02 master branch
go version:  go1.14.15 linux/amd64

test code:
```go
func TestRBACModelInMemory(t *testing.T) {
	m := model.NewModel()
	m.AddDef("r", "r", "sub, obj, act")
	m.AddDef("p", "p", "sub, obj, act")
	m.AddDef("g", "g", "_, _")
	m.AddDef("e", "e", "some(where (p.eft == allow))")
	m.AddDef("m", "m", "g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act")

	e, _ := NewEnforcer(m)

	_, _ = e.AddPermissionForUser("alice", "data1", "read")
	_, _ = e.AddPermissionForUser("bob", "data2", "write")
	_, _ = e.AddPermissionForUser("data2_admin", "data2", "read")
	_, _ = e.AddPermissionForUser("data2_admin", "data2", "write")
	_, _ = e.AddRoleForUser("alice", "data2_admin")

	testEnforce(t, e, "alice", "data1", "read", true)
	testEnforce(t, e, "alice", "data1", "write", false)
	testEnforce(t, e, "alice", "data2", "read", true)
	testEnforce(t, e, "alice", "data2", "write", true)
	testEnforce(t, e, "bob", "data1", "read", false)
	testEnforce(t, e, "bob", "data1", "write", false)
	testEnforce(t, e, "bob", "data2", "read", false)
	testEnforce(t, e, "bob", "data2", "write", true)

	var wg sync.WaitGroup

	//bChan := make(chan struct{}, 1000)

	for i := 0; i < 5000; i++ {
		wg.Add(1)
		go func(i int) {
			defer func() {
				wg.Done()
			}()
			if i %2 == 0 {
				_, err := e.AddPermissionForUser(fmt.Sprintf("alice_%d", i), "data1", "read")
				if err != nil {
					log.Println(err)
				}
				return
			}
			testEnforce(t, e, fmt.Sprintf("alice_%d", i), "data1", "read", true)
		}(i)
	}

	wg.Wait()
}
```

error: 
```
fatal error: concurrent map writes

goroutine 48 [running]:
runtime.throw(0x64b2ab, 0x15)
	/opt/go/src/runtime/panic.go:1116 +0x72 fp=0xc000186c58 sp=0xc000186c28 pc=0x435492
runtime.mapassign_faststr(0x60ee40, 0xc000070ba0, 0xc000206020, 0x13, 0xc000073b58)
	/opt/go/src/runtime/map_faststr.go:211 +0x3f7 fp=0xc000186cc0 sp=0xc000186c58 pc=0x413d37
github.com/casbin/casbin/v2/model.Model.AddPolicy(0xc000070ab0, 0x6469ef, 0x1, 0x6469ef, 0x1, 0xc000204030, 0x3, 0x3)
	/home/wangy/workspace/casbin/model/policy.go:168 +0x25b fp=0xc000186d40 sp=0xc000186cc0 pc=0x55cccb
github.com/casbin/casbin/v2.(*Enforcer).addPolicy(0xc00012e380, 0x6469ef, 0x1, 0x6469ef, 0x1, 0xc000204030, 0x3, 0x3, 0xc000204010, 0xc000160780, ...)
	/home/wangy/workspace/casbin/internal_api.go:51 +0x1d7 fp=0xc000186de0 sp=0xc000186d40 pc=0x590be7
github.com/casbin/casbin/v2.(*Enforcer).AddNamedPolicy(0xc00012e380, 0x6469ef, 0x1, 0xc0001606e8, 0x1, 0x1, 0x2, 0x2, 0x4d1434)
	/home/wangy/workspace/casbin/management_api.go:138 +0x2f6 fp=0xc000186e80 sp=0xc000186de0 pc=0x594a96
github.com/casbin/casbin/v2.(*Enforcer).AddPolicy(...)
	/home/wangy/workspace/casbin/management_api.go:122
github.com/casbin/casbin/v2.(*Enforcer).AddPermissionForUser(0xc00012e380, 0xc000200010, 0x8, 0xc000160780, 0x2, 0x2, 0x8, 0x0, 0x0)
	/home/wangy/workspace/casbin/rbac_api.go:128 +0x1a2 fp=0xc000186f20 sp=0xc000186e80 pc=0x597c82
github.com/casbin/casbin/v2.TestRBACModelInMemory22.func1(0xc000022e70, 0xc00012e380, 0xc000110360, 0x28)
	/home/wangy/workspace/casbin/enforcer_test.go:152 +0x149 fp=0xc000186fc0 sp=0xc000186f20 pc=0x5d5df9
runtime.goexit()
	/opt/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000186fc8 sp=0xc000186fc0 pc=0x467061
created by github.com/casbin/casbin/v2.TestRBACModelInMemory22
	/home/wangy/workspace/casbin/enforcer_test.go:147 +0x7f3
```

**Comment by dollarkillerx** [comment]
batch 2.x    Also there is a problem

**Comment by hsluoyz** [comment]
@closetool @tangyang9464 plz resolve it as first priority.

**Comment by closetool** [comment]
@hsluoyz @dollarkillerx Should use `SyncedEnforcer`.

**Comment by hsluoyz** [comment]
@dollarkillerx see also: https://casbin.org/docs/en/multi-threading
