### ISSUE TITLE
[Bug]Concurrent map read and map write in SyncedEnforcer

### ISSUE THREAD

**Issue by phoenixsqf** [casbin/casbin#888]
**Describe the bug**

here is the stack

```
fatal error: concurrent map read and map write

goroutine 618 [running]:
runtime.throw(0x1a47826, 0x21)
        /usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc000b1c6b0 sp=0xc000b1c680 pc=0x436672
runtime.mapaccess2_faststr(0x18199c0, 0xc00006eab0, 0xc000c44dc0, 0x1f, 0x2, 0xc000c44dc0)
        /usr/local/go/src/runtime/map_faststr.go:116 +0x4a5 fp=0xc000b1c720 sp=0xc000b1c6b0 pc=0x4141a5
github.com/casbin/casbin/v2/rbac/default-role-manager.(*RoleManager).domainMatch(0xc0000c6140, 0xc000c44a20, 0x17, 0xc00084c4a8, 0x6, 0x70000c000b08300)
        /root/go/pkg/mod/github.com/casbin/casbin/v2@v2.37.0/rbac/default-role-manager/role_manager.go:376 +0xd6 fp=0xc000b1c7a0 sp=0xc000b1c720 pc=0xe25216
github.com/casbin/casbin/v2/rbac/default-role-manager.(*RoleManager).getPatternDomain.func1(0x17ba520, 0xc000a4d7b0, 0x1927080, 0xc000a20bd0, 0x17c4d01)
        /root/go/pkg/mod/github.com/casbin/casbin/v2@v2.37.0/rbac/default-role-manager/role_manager.go:195 +0x8d fp=0xc000b1c820 sp=0xc000b1c7a0 pc=0xe26bcd
sync.(*Map).Range(0xc00006ea20, 0xc000b1c920)
        /usr/local/go/src/sync/map.go:345 +0x1d9 fp=0xc000b1c8f8 sp=0xc000b1c820 pc=0x484659
github.com/casbin/casbin/v2/rbac/default-role-manager.(*RoleManager).getPatternDomain(0xc0000c6140, 0xc000c44a20, 0x17, 0x10, 0x10, 0x17c4d40)
        /root/go/pkg/mod/github.com/casbin/casbin/v2@v2.37.0/rbac/default-role-manager/role_manager.go:192 +0xf5 fp=0xc000b1c958 sp=0xc000b1c8f8 pc=0xe23f15
github.com/casbin/casbin/v2/rbac/default-role-manager.(*RoleManager).HasLink(0xc0000c6140, 0xc000c44a00, 0x12, 0xc00037d5e0, 0xe, 0xc000949e80, 0x1, 0x1, 0x3a, 0xdfb914, ...)
        /root/go/pkg/mod/github.com/casbin/casbin/v2@v2.37.0/rbac/default-role-manager/role_manager.go:215 +0xb4 fp=0xc000b1ca38 sp=0xc000b1c958 pc=0xe23ff4
github.com/casbin/casbin/v2/util.GenerateGFunction.func1(0xc000aa6e00, 0x3, 0x4, 0x0, 0x26a0a60, 0x0, 0x0)
        /root/go/pkg/mod/github.com/casbin/casbin/v2@v2.37.0/util/builtin_operators.go:333 +0x30d fp=0xc000b1cb18 sp=0xc000b1ca38 pc=0xe1078d
github.com/Knetic/govaluate.makeFunctionStage.func1(0x0, 0x0, 0x177eb60, 0xc000b08380, 0x1c1bda0, 0xc000949e60, 0x0, 0x0, 0xc7, 0xc000a857c0)
        /root/go/pkg/mod/github.com/!knetic/govaluate@v3.0.1-0.20171022003610-9aa49832a739+incompatible/evaluationStage.go:243 +0x72 fp=0xc000b1cb68 sp=0xc000b1cb18 pc=0xe07752
github.com/Knetic/govaluate.EvaluableExpression.evaluateStage(0x1a48b85, 0x22, 0x1, 0xc00051c600, 0x39, 0x40, 0xc00087c5a0, 0xc00015c0d0, 0xc7, 0xc000a85810, ...)
        /root/go/pkg/mod/github.com/!knetic/govaluate@v3.0.1-0.20171022003610-9aa49832a739+incompatible/EvaluableExpression.go:232 +0x174 fp=0xc000b1cc48 sp=0xc000b1cb68 pc=0xdfb914
github.com/Knetic/govaluate.EvaluableExpression.evaluateStage(0x1a48b85, 0x22, 0x1, 0xc00051c600, 0x39, 0x40, 0xc00087c5a0, 0xc00015c0d0, 0xc7, 0xc00087c3c0, ...)
        /root/go/pkg/mod/github.com/!knetic/govaluate@v3.0.1-0.20171022003610-9aa49832a739+incompatible/EvaluableExpression.go:172 +0x6c9 fp=0xc000b1cd28 sp=0xc000b1cc48 pc=0xdfbe69
github.com/Knetic/govaluate.EvaluableExpression.evaluateStage(0x1a48b85, 0x22, 0x1, 0xc00051c600, 0x39, 0x40, 0xc00087c5a0, 0xc00015c0d0, 0xc7, 0xc00087c410, ...)
        /root/go/pkg/mod/github.com/!knetic/govaluate@v3.0.1-0.20171022003610-9aa49832a739+incompatible/EvaluableExpression.go:172 +0x6c9 fp=0xc000b1ce08 sp=0xc000b1cd28 pc=0xdfbe69
github.com/Knetic/govaluate.EvaluableExpression.evaluateStage(0x1a48b85, 0x22, 0x1, 0xc00051c600, 0x39, 0x40, 0xc00087c5a0, 0xc00015c0d0, 0xc7, 0xc00087c460, ...)
        /root/go/pkg/mod/github.com/!knetic/govaluate@v3.0.1-0.20171022003610-9aa49832a739+incompatible/EvaluableExpression.go:172 +0x6c9 fp=0xc000b1cee8 sp=0xc000b1ce08 pc=0xdfbe69
github.com/Knetic/govaluate.EvaluableExpression.evaluateStage(0x1a48b85, 0x22, 0x1, 0xc00051c600, 0x39, 0x40, 0xc00087c5a0, 0xc00015c0d0, 0xc7, 0xc00087c4b0, ...)
        /root/go/pkg/mod/github.com/!knetic/govaluate@v3.0.1-0.20171022003610-9aa49832a739+incompatible/EvaluableExpression.go:172 +0x6c9 fp=0xc000b1cfc8 sp=0xc000b1cee8 pc=0xdfbe69
github.com/Knetic/govaluate.EvaluableExpression.evaluateStage(0x1a48b85, 0x22, 0x1, 0xc00051c600, 0x39, 0x40, 0xc00087c5a0, 0xc00015c0d0, 0xc7, 0xc00087c500, ...)
        /root/go/pkg/mod/github.com/!knetic/govaluate@v3.0.1-0.20171022003610-9aa49832a739+incompatible/EvaluableExpression.go:172 +0x6c9 fp=0xc000b1d0a8 sp=0xc000b1cfc8 pc=0xdfbe69
github.com/Knetic/govaluate.EvaluableExpression.evaluateStage(0x1a48b85, 0x22, 0x1, 0xc00051c600, 0x39, 0x40, 0xc00087c5a0, 0xc00015c0d0, 0xc7, 0xc00087c550, ...)
        /root/go/pkg/mod/github.com/!knetic/govaluate@v3.0.1-0.20171022003610-9aa49832a739+incompatible/EvaluableExpression.go:172 +0x6c9 fp=0xc000b1d188 sp=0xc000b1d0a8 pc=0xdfbe69
github.com/Knetic/govaluate.EvaluableExpression.evaluateStage(0x1a48b85, 0x22, 0x1, 0xc00051c600, 0x39, 0x40, 0xc00087c5a0, 0xc00015c0d0, 0xc7, 0xc00087c5a0, ...)
        /root/go/pkg/mod/github.com/!knetic/govaluate@v3.0.1-0.20171022003610-9aa49832a739+incompatible/EvaluableExpression.go:172 +0x6c9 fp=0xc000b1d268 sp=0xc000b1d188 pc=0xdfbe69
github.com/Knetic/govaluate.EvaluableExpression.Eval(0x1a48b85, 0x22, 0x1, 0xc00051c600, 0x39, 0x40, 0xc00087c5a0, 0xc00015c0d0, 0xc7, 0x1c1e980, ...)
        /root/go/pkg/mod/github.com/!knetic/govaluate@v3.0.1-0.20171022003610-9aa49832a739+incompatible/EvaluableExpression.go:163 +0xb9 fp=0xc000b1d2f8 sp=0xc000b1d268 pc=0xdfb6d9
github.com/casbin/casbin/v2.(*Enforcer).enforce(0xc0000f4600, 0x0, 0x0, 0x0, 0xc00086ee70, 0xb, 0xb, 0xc0007cba00, 0x0, 0x0)
        /root/go/pkg/mod/github.com/casbin/casbin/v2@v2.37.0/enforcer.go:587 +0x1405 fp=0xc000b1d878 sp=0xc000b1d2f8 pc=0xe2ad65
github.com/casbin/casbin/v2.(*Enforcer).Enforce(...)
        /root/go/pkg/mod/github.com/casbin/casbin/v2@v2.37.0/enforcer.go:686
github.com/casbin/casbin/v2.(*SyncedEnforcer).Enforce(0xc00006e060, 0xc00086ee70, 0xb, 0xb, 0x0, 0x0, 0x0)
        /root/go/pkg/mod/github.com/casbin/casbin/v2@v2.37.0/enforcer_synced.go:148 +0xb5 fp=0xc000b1d8f0 sp=0xc000b1d878 pc=0xe2d395

```

my init code is like 

```
enforcer, err := casbin.NewSyncedEnforcer(modelPath)
if err != nil {
    return nil, err
}
enforcer.GetRoleManager().(*defaultrolemanager.RoleManager).AddDomainMatchingFunc("", util.KeyMatch)
return enforcer, nil
```

**Comment by tangyang9464** [comment]
@phoenixsqf Can I have your code that caused the error?

**Comment by phoenixsqf** [comment]
@tangyang9464 Sorry I only meet this error once. And I dont know how to make the error reappeared because it happened in a complex scene.
Maybe concurrenttly do enforce and add role for user?

**Comment by tangyang9464** [comment]
@phoenixsqf What casbin version are you using?

**Comment by phoenixsqf** [comment]
@tangyang9464 sry for forgetitng it. Im using v2.37.0.

**Comment by tangyang9464** [comment]
@phoenixsqf 
https://github.com/casbin/casbin/blob/74a03c56dda888c69eff820f7f684b066995fb0e/rbac/default-role-manager/role_manager.go#L42-L43
https://github.com/casbin/casbin/blob/74a03c56dda888c69eff820f7f684b066995fb0e/rbac/default-role-manager/role_manager.go#L376-L381
I think it should be the problem here, the map ``domainMatchingFuncCache`` is not concurrency safe

**Comment by phoenixsqf** [comment]
@tangyang9464 Thx. Should the cache be a concurrent read write map but not a syncMap？

**Comment by Garagator3000** [comment]
This error apparently has not been fixed.

go 1.22.4
github.com/casbin/casbin/v2 v2.71.1

This error was seen twice on the project.
Unfortunately, panics from sync.Mutex cannot be caught via recover().

```
...
goroutine 104658 [running]:
sync.fatal({0x10f316c?, 0xf92de0?})
	/usr/local/go/src/runtime/panic.go:1007 +0x18
sync.(*Mutex).unlockSlow(0xc00039e248, 0xffffffff)
	/usr/local/go/src/sync/mutex.go:229 +0x35
sync.(*Mutex).Unlock(...)
	/usr/local/go/src/sync/mutex.go:223
sync.(*Map).Swap(0xc00039e248, {0xee7f40, 0xc0009786d0}, {0x1039740, 0xc000ba0870})
	/usr/local/go/src/sync/map.go:367 +0x35c
sync.(*Map).Store(...)
	/usr/local/go/src/sync/map.go:155
github.com/casbin/casbin/v2.(*Enforcer).getAndStoreMatcherExpression(0x0?, 0x0, {0xc000353600, 0x75}, 0xc00092cf90)
	/go/pkg/mod/github.com/casbin/casbin/v2@v2.71.1/enforcer.go:726 +0xb9
github.com/casbin/casbin/v2.(*Enforcer).enforce(0xc00039e1e0, {0x0, 0x0}, 0x0, {0xc00092cf30, 0x3, 0x3})
	/go/pkg/mod/github.com/casbin/casbin/v2@v2.71.1/enforcer.go:579 +0x9e5
github.com/casbin/casbin/v2.(*Enforcer).Enforce(...)
	/go/pkg/mod/github.com/casbin/casbin/v2@v2.71.1/enforcer.go:733
{PRIVATE}/usecases/permission.(*Usecase).CheckPolicy(0xc000820e10, {0x1e?, 0xc0011681b0?}, {0x131d7a8, 0xc00093bad0})
	/go/src/app/internal/app/a5/usecases/permission/usecase.go:168 +0x5ac
...
```
